<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="data\dealer.png" />
    <None Remove="data\decks\default\cards_sheet.png" />
    <None Remove="data\player.png" />
    <None Remove="data\pokertable.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\SettingsPage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\GameInfoPage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="data\dealer.png" />
    <Resource Include="data\decks\default\cards_sheet.png" />
    <Resource Include="data\player.png" />
    <Resource Include="data\pokertable.png" />
  </ItemGroup>

</Project>
